Insert into PARTITION_METADATA (OWNER,TABLE_NAME,PARTITION_FREQUENCY,PARTITION_NAME_FORMAT,PARTITION_TS_FORMAT,FIRST_PARTITION_NAME,MAXVAL_PARTITION_NAME,MAXVAL_TS_NAME_FORMAT,NUM_ADVANCE_PARTITIONS,ACTIVE_RECORD_FLAG,DW_UPDATED_BY,DW_LAST_UPDATED)
 values ('DWH','SALES','DAILY','P{yyyy}{mm}{dd}','DWH_SALES_DAT','P20100101','PMAX','DWH_SALES_DATA',10,'Y','DBMAINTUSER',sysdate);

Insert into PARTITION_METADATA (OWNER,TABLE_NAME,PARTITION_FREQUENCY,PARTITION_NAME_FORMAT,PARTITION_TS_FORMAT,FIRST_PARTITION_NAME,MAXVAL_PARTITION_NAME,MAXVAL_TS_NAME_FORMAT,NUM_ADVANCE_PARTITIONS,ACTIVE_RECORD_FLAG,DW_UPDATED_BY,DW_LAST_UPDATED)
  values ('DWH','SALES_MONTHLY','MONTHLY','P{yyyy}{mm}','DWH_SALES_DATA','P20100101','PMAX','DWH_SALES_DATA',2,'Y','DBMAINTUSER',sysdate);

commit;

